language: node_js

node_js:
    - "node"
    - "12"
    # - "10"
    # - "8"
    # - "6"

sudo: false

git:
    submodules: false

services:
    - mongodb

before_script:
    - npm install
    - sleep 15
    - mongo trading --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
